version: '2'
services:
    src:
        image: busybox
        stdin_open: true
        tty: true
        restart: always
        volumes:                                                                
            - $PWD/src:$PWD/src
            - $PWD/src
    dev:
        image: python:3
        working_dir: $PWD/src
        expose:                                                                 
            - 5000
        env_file: .env
        volumes_from:                                                                
            - src
        volumes:
            - $PWD/src
        command: /bin/bash -c 'python -m venv --copies --clear venv && venv/bin/pip install --no-cache-dir -r requirements.txt && venv/bin/gunicorn -w 2 -b :5000 app:app'

    nginx:
        image: tutum/nginx
        ports:
          - 80:80
          - 443:443
        links:
            - dev:backend
        volumes:
          - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
