version: '2'
services:
    src:
        image: busybox
        volumes:
            - $PWD/src:/opt/app
            - /opt/app
    dev:
        image: python
        working_dir: /opt/app
        environment:
            - DEBUG=True
        volumes_from:
            - src
        command: /bin/bash -c 'python -m venv --copies --clear venv && venv/bin/pip install --no-cache-dir -r dev.txt && sed -i "s/^#\!.*/#\!venv\/bin\/python/" venv/bin/*'

    data:
        image: postgres:latest
        volumes:
            - /var/lib/postgresql
        command: "true"

    postgres:
        restart: always
        image: postgres:latest
        volumes_from:
            - data
        ports:
            - "5432:5432"

    gunicorn:
        #        build:
            #            context: ./src/
            #            dockerfile: Dockerfile_gunicorn
        image: python
        restart: always
        working_dir: /opt/app/
        expose:
            - 5000
        env_file: .env
        environment:
            - DEBUG=False
        links:
            - postgres:db
        volumes_from:
            - src
        command: /bin/bash -c 'pip install gunicorn -r requirements.txt && gunicorn -w 2 -b :5000 app:app'

    nginx:
        image: tutum/nginx
        ports:
          - 80:80
          - 443:443
        links:
            - gunicorn:backend
        volumes:
          - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
